### ISSUE TITLE
No current solution for ignoring `#[tokio::main]` on sync

### ISSUE THREAD

**Issue by juliankrieger** [fMeow/maybe-async-rs#13]
As written in the title, I don't think there is currently a solution to only spit out attributes with `maybe_async`. Am I overlooking things? I want the following to compile:

```
#[tokio::main]
 #[maybe_async::maybe_async]
 async fn main() {
     let user = User::new("kasuporo");
     // Now you are able to:

     // Get overview
     let overview = user.overview(None).await;

     // Get submitted posts.
     let submitted = user.submitted(None).await;

     // Get comments.
     let comments = user.comments(None).await;
 }
```
The `maybe_async` attribute works fine when `is_sync` is enabled but the resolved code is the following:

```
#[tokio::main]
 fn main() {
     let user = User::new("kasuporo");
     // Now you are able to:

     // Get overview
     let overview = user.overview(None);

     // Get submitted posts.
     let submitted = user.submitted(None);

     // Get comments.
     let comments = user.comments(None);
 }
```

Sadly, `tokio::main` remains. Is there something I am missing?

**Comment by NobodyXu** [comment]
You could write `#[cfg_attr(feature = "..", tokio::main)]`, since it is likely that your crate itself has a feature flag for sync/async mode.

**Comment by juliankrieger** [comment]
I didn't think of using `cfg_attr`. I'll be closing the issue now.
