### ISSUE TITLE
Unable to compile a project with two different crates that use maybe_async (one async and another blocking)

### ISSUE THREAD

**Issue by mdecimus** [fMeow/maybe-async-rs#19]
Hi,

I am trying to compile a project that depends on two crates that use `maybe-async` internally. One crate sets the `is_sync` flag while the other doesn't. The problem I am having is that the `is_sync` flag set by one crate is applied also to the other crate that requires async and the project fails to compile. All projects use resolver v2.

I believe this problem was discussed in this [Reddit post](https://www.reddit.com/r/rust/comments/g6lc98/maybeasync_unifying_async_and_sync_implement_for/).

**Comment by mdecimus** [comment]
Update: This seems to be due to cargo's [feature unification](https://doc.rust-lang.org/1.59.0/cargo/reference/features.html#feature-unification). Here are some [possible fixes](https://www.reddit.com/r/rust/comments/sgegah/cargo_features_have_to_be_additive/).

**Comment by fMeow** [comment]
This is a major known issue. The `maybe-async` crate just simply violates the additive rules for feature gates. 

A possible better solution is to duplicate the marked code to offer both async and sync impl. But this is is not easy, especially I have written a working demo but the compiler error message messed up.

**Comment by mdecimus** [comment]
For the time being I'll just duplicate the maybe_async code in a separate crate so the features don't create conflicts. Thanks.
